language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

before_install:
  - nvm install 5.1

before_script:
  - cp .env.travis .env


install:
  - travis_retry composer install

script:
  - vendor/bin/phpunit
